// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhhJBvmzGk8ITfStWgx8oLQUFkvE8zujk',
    appId: '1:1046577808922:web:b5b5a94198adce68b8f3a3',
    messagingSenderId: '1046577808922',
    projectId: 'ostaad-88d1f',
    authDomain: 'ostaad-88d1f.firebaseapp.com',
    storageBucket: 'ostaad-88d1f.firebasestorage.app',
    measurementId: 'G-KPPDHGF4XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnsIhHeLg9QTA_VrvvME_ssuox0uOm4aY',
    appId: '1:1046577808922:android:df28029a176c1dd1b8f3a3',
    messagingSenderId: '1046577808922',
    projectId: 'ostaad-88d1f',
    storageBucket: 'ostaad-88d1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzyEt_TJelRDBmLvgud9bvmv-TlPoTFjM',
    appId: '1:1046577808922:ios:419fcc3475e8cde1b8f3a3',
    messagingSenderId: '1046577808922',
    projectId: 'ostaad-88d1f',
    storageBucket: 'ostaad-88d1f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFigma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzyEt_TJelRDBmLvgud9bvmv-TlPoTFjM',
    appId: '1:1046577808922:ios:419fcc3475e8cde1b8f3a3',
    messagingSenderId: '1046577808922',
    projectId: 'ostaad-88d1f',
    storageBucket: 'ostaad-88d1f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFigma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhhJBvmzGk8ITfStWgx8oLQUFkvE8zujk',
    appId: '1:1046577808922:web:a2b329fb202f25f5b8f3a3',
    messagingSenderId: '1046577808922',
    projectId: 'ostaad-88d1f',
    authDomain: 'ostaad-88d1f.firebaseapp.com',
    storageBucket: 'ostaad-88d1f.firebasestorage.app',
    measurementId: 'G-EYZR81P4CG',
  );
}
